3rd commit of first lession

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -4,16 +4,14 @@ on: push
 jobs:
     echo-hello:
         runs-on: ubuntu-latest
-        name: echo-hello
         steps: 
             - name: Say hello
               run: echo "Started job"
     echo-goobye_with-error:
         runs-on: ubuntu-latest
-        name: Failed
         steps:
             - name: Failed
               run: |
-                echo "Failed step failed"
-                exit 1
+                    echo "Failed step failed"
+                    exit 1
 
